name: kaggle-pubg
channels:
  - pytorch
  - conda-forge
  - default
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - keras
  - scikit-learn
  - pytorch
  - torchvision
  - cython
  - jupyter
  - nb_conda_kernels
  - Pillow
